### ISSUE TITLE
Не запускается docker-compose

### ISSUE THREAD

**Issue by supremko** [supremko/docker#1]
Система Windows 10 Pro 1903
При попытке запуска - docker-compose up -d отображается ошибка
![image](https://user-images.githubusercontent.com/505723/71324046-37c82700-24eb-11ea-832d-cd75f8f77e86.png)
Попытка перенести проект на диск С или запустить в режиме администратора никак не помогли.
Docker Desktop при этом установлен.

**Comment by ArRomanov** [comment]
Вы пробовали решения, описанные по этим ссылкам?
1. https://blogs.msdn.microsoft.com/stevelasker/2016/06/14/configuring-docker-for-windows-volumes/
2. https://github.com/docker/compose/issues/4303

Похоже, что у вас не донастроен docker desktop. По первой ссылке просмотрите все рекомендации

**Comment by supremko** [comment]
Действительно, в Docker Desktop необходимо еще указать какие диски расшарены для работы. После расшаривания команда сработала, но отобразилось окно изменения конфигурации с ошибкой Unable to auto-detect settings, manual configuration requeried, но не понятно, что именно настроить надо в инструкции https://github.com/netology-code/aqa-homeworks/tree/master/docker этого не вижу

![image](https://user-images.githubusercontent.com/505723/71325315-0015ab00-24fc-11ea-82ad-09a7edd5c7c5.png)

**Comment by ArRomanov** [comment]
Вот в этой инструкции достаточно подробно рассказано про настройку docker в интерфейсе IDEA - https://www.jetbrains.com/help/idea/docker.html. Но это не является обязательным, даже нежелательно. Вам стоит больше уделять вниманию при работе с docker и docker-compose через интерфейс командной строки, потому что не всегда у вас будет возможность пользоваться интерфейсом (например на удаленном сервере). Поэтому старайтесь выполнять все команды в консоли, тем более основных не так много, чтобы они вызывали какие-либо сложности

**Comment by supremko** [comment]
Интерфейс появился именно после выполнения команды docker-compose up -d, я его не вызывал специально. Сейчас попробовал снова запустить и он не отобразил ошибки, хотя я ничего не менял, закрою тогда...
